### ISSUE TITLE
No adduct generation

### ISSUE THREAD

**Issue by samuelcajahuaringa** [pnnl/isicle#29]
Hello Isicle developers,

I try to reproduce the example of collision cross section. The Isicle was installed correctly according to the message

```
Requirement already satisfied: certifi>=2017.4.17 in /home/oscar.macollunco/anaconda3/envs/isicle/lib/python3.9/site-packages (from requests->snakemake>=6.3.0->isicle==2.0.0) (2024.2.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/oscar.macollunco/anaconda3/envs/isicle/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->gitpython->snakemake>=6.3.0->isicle==2.0.0) (5.0.0)
Requirement already satisfied: platformdirs>=2.5 in /home/oscar.macollunco/anaconda3/envs/isicle/lib/python3.9/site-packages (from jupyter-core->nbformat->snakemake>=6.3.0->isicle==2.0.0) (4.2.0)
Installing collected packages: isicle
  Running setup.py develop for isicle
Successfully installed isicle-2.0.0
```

the structure of example is dimethylglycine.mol 

```
 OpenBabel03092420292D

 16 15  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  8  1  0  0  0  0
  1  9  1  0  0  0  0
  1 10  1  0  0  0  0
  2  3  1  0  0  0  0
  2  4  1  0  0  0  0
  3 11  1  0  0  0  0
  3 12  1  0  0  0  0
  3 13  1  0  0  0  0
  4  5  1  0  0  0  0
  4 14  1  0  0  0  0
  4 15  1  0  0  0  0
  5  6  2  0  0  0  0
  5  7  1  0  0  0  0
  7 16  1  0  0  0  0
M  END
```

I am trying to get started using isicle but im running into an issue when following the CCS example presented [here](https://isicle.readthedocs.io/en/latest/user_guide/CCS.html).

```
(isicle) oscar.macollunco@sorgan-cpu6:~/isicle$ python
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import isicle
>>> geom = isicle.io.load('dimethylglycine.mol')
>>> geom = geom.initial_optimize(embed=True)
>>> adducts = geom.ionize(method = 'explicit', ion_list = ['H+'], element_list = ['O', 'N'])
>>> adducts = isicle.io.load('ccs_adducts.joblib')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oscar.macollunco/isicle/isicle/io.py", line 465, in load
    return load_joblib(path)
  File "/home/oscar.macollunco/isicle/isicle/io.py", line 384, in load_joblib
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ccs_adducts.joblib'
>>> 
```

where i found the 'ccs_adducts.joblib' that is a job submission file? can you send me a example.

Any help would be much appreciated.

**Comment by smcolby** [comment]
The line `adducts = geom.ionize(method = 'explicit', ion_list = ['H+'], element_list = ['O', 'N'])` will have generated possible adducts. Downstream activities would include conformational sampling by molecular dynamics, conformer downselection, density functional theory-based geometry optimization, and, finally, CCS prediction.

These tasks have all been developed as [snakemake](https://snakemake.readthedocs.io/en/stable/) and [joblib](https://joblib.readthedocs.io/en/stable/) workflows, which you found. However, these are intended to be run outside the ISiCLE API. For example, snakemake is invoked as `snakemake --snakefile PATH {ARGS}`. 

We currently do not have documentation detailing the workflow usage, so I would encourage you to familiarize yourself with snakemake and/or joblib documentation.

**Comment by samuelcajahuaringa** [comment]
Thanks for the advice @smcolby, if possible use the ccs.nf to test that example, the ccs.bf file that is found in workflows/ccs/nextflow-local/ccs.nf.

**Comment by samuelcajahuaringa** [comment]
Hello isicile developers, I have installed nextflow and I try to use ccs.nf file but I have the follow problem:
(isicle) oscar.macollunco@sorgan-cpu6:~/isicle/workflows/ccs/nextflow-local$ nextflow run ccs.nf -config nextflow.config
N E X T F L O W  ~  version 23.10.1
Launching `ccs.nf` [jolly_panini] DSL2 - revision: 5f2e891df9
ERROR ~ Unknown process directive: `publishdir`

Did you mean of these?
        publishDir

 -- Check script 'ccs.nf' at line: 79 or see '.nextflow.log' file for more details
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:67)
	at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:250)
	at jline.internal.ShutdownHooks.addHook(ShutdownHooks.java:79)
	at jline.internal.ShutdownHooks.add(ShutdownHooks.java:43)
	at jline.TerminalSupport.init(TerminalSupport.java:46)
	at jline.UnixTerminal.init(UnixTerminal.java:47)
	at jline.TerminalFactory.create(TerminalFactory.java:101)
	at jline.TerminalFactory.get(TerminalFactory.java:159)
	at nextflow.trace.AnsiLogObserver.renderProcesses(AnsiLogObserver.groovy:249)
	at nextflow.trace.AnsiLogObserver.renderProgress(AnsiLogObserver.groovy:289)
	at nextflow.trace.AnsiLogObserver.render0(AnsiLogObserver.groovy:177)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1254)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1042)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1128)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:498)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)

[-        ] process > adducts    -
[-        ] process > conformers -

**Comment by smcolby** [comment]
I am actually not familiar with NextFlow (I've used Snakemake). I'm copying @jessbade here, as she has more experience with NextFlow.
