### ISSUE TITLE
Problems running isicle under windows 11

### ISSUE THREAD

**Issue by steto123** [pnnl/isicle#38]
Hello Isicle Team,

after solving some problems using openbabel i was happy to run a python example. Therefore i have copied collision_cross_section.py in the isicle root directory and run it. And now i have some errors:

(isicle-env) PS D:\isicle> python collision_cross_section.py
Syntaxfehler.
Traceback (most recent call last):
  File "D:\isicle\collision_cross_section.py", line 18, in <module>
    md_result = adduct.md(program='xtb',
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\isicle\isicle\geometry.py", line 110, in md
    return isicle.md.md(self, program=program, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\isicle\isicle\md.py", line 66, in md
    return _program_selector(program).run(geom, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\isicle\isicle\md.py", line 444, in run
    self.finish()
  File "D:\isicle\isicle\md.py", line 391, in finish
    parser.load(os.path.join(self.temp_dir, self.basename + ".out"))
  File "D:\isicle\isicle\parse.py", line 948, in load
    with open(path, "r") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\wotan\\AppData\\Local\\Temp\\isicle\\tmpysuh0yui\\FERIUCNNQQJTOY-UHFFFAOYSA-N.out'

Can you help? An i have read, about a tutorial. Where i can find it?

Many thanks!

Steffen

**Comment by steto123** [comment]
Installling isicle in WSL2 is working, but python collision_cross_section.py ends with

CREST terminated normally 


and nothing more.

**Comment by smcolby** [comment]
Apologies that you are having trouble with ISiCLE. Note that there is currently no command line interface, so `isicle --help` will not produce any output.

I just tried running the `collision_cross_section.py` script on my machine, and it appears some of the code is not up to date with the latest changes. I will fix and report back this week.
